<?php

namespace AppBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository {

    public function getCategories() {
        $qb = $this->createQueryBuilder('a');
        $qb->orderBy('a.titre', 'DESC');
        $querry = $qb->getQuery();
        $categorie = $querry->getResult();
        return $categorie;
    }

}
