<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Categorie;
use Doctrine\ORM\EntityRepository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends EntityRepository {

    public function getProduitsByCategorie(Categorie $cat) {
        $qb = $this->createQueryBuilder('a');
        $qb->leftJoin('a.image', 'i')
                ->addSelect('i')
                ->leftJoin('a.notes', 'n')
                ->addSelect('n')
                ->leftJoin('a.categorie', 'c')
                ->addSelect('c')
                ->where('a.categorie = ?1')
                ->setParameter(1, $cat)
                ->orderBy('a.date', 'DESC');
        //
        $querry = $qb->getQuery();
        $produits = $querry->getArrayResult(); // equivalent d'un fetch
        return $produits;
    }

    public function getProduitByIdWithJoin($id) {
        $qb = $this->createQueryBuilder('p');
        $qb->leftJoin('p.image', 'i')
                ->addSelect('i')
                ->leftJoin('p.notes', 'n')
                ->addSelect('n')
                ->leftJoin('p.categorie', 'c')
                ->addSelect('c')
                ->where('p.id = ?1')//andWhere('a.id = ?2')
                ->setParameter(1, $id);

        $querry = $qb->getQuery();
        $produit = $querry->getOneOrNullResult();
        return $produit;
    }

}
